services:
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: karaoke_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://karaoke_user:karaoke_pass@db:5432/karaoke
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: karaoke_db
    environment:
      POSTGRES_USER: karaoke_user
      POSTGRES_PASSWORD: karaoke_pass
      POSTGRES_DB: karaoke
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
volumes:
  db_data:
